apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart-service
        image: "{{ .Values.docker.image }}:{{ .Values.docker.tag }}"
        ports:
        - containerPort: 8000
          name: http
