apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
    name: order-rollout
    labels:
        app: order
spec:
    replicas: 3
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app: order
    template:
        metadata:
            labels:
                app: order
        spec:
            containers:
                - name: order-service
                  image: "{{ .Values.order.image }}:{{ .Values.order.tag }}"
                  ports:
                    - containerPort: 8000
                      name: http
    strategy:
        canary:
            steps:
                - setWeight: 20
                - pause: {}
                - setWeight: 40
                - pause: { duration: 10s }
                - setWeight: 60
                - pause: { duration: 10s }
                - setWeight: 80
                - pause: { duration: 10s}