name: CI/CD Pipeline
on:
  push:
    branches: ["master"]
jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install fastapi uvicorn
      - name: Run Unit Tests
        run: echo "No tests yet."
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: docker/cart-serivce
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_URL: "https://sonarcloud.io"
      - name: Docker Login
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push Docker Image
        run: |
          docker build -t nethuy/cart-service:latest
          docker push nethuy/cart-service:latest
