name: CI/CD Pipeline
on:
  push:
    branches: ["master"]
jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install fastapi uvicorn

      - name: Run Unit Tests
        run: echo "No tests yet."

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=nethuy_cart-service
            -Dsonar.organization=nethuy
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectBaseDir=docker/cart-service

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t nethuy/cart-service:latest docker/cart-service
          docker push nethuy/cart-service:latest
